# Generated by Django 4.1.7 on 2023-04-02 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0002_rename_item_names_product_item_name_sale'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='received',
            new_name='received_quantity',
        ),
        migrations.AlterField(
            model_name='sale',
            name='amount_received',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='sale',
            name='quantity',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='sale',
            name='unit_price',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
